name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'
    
    - name: Run Tests
      run: swift test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/calorista
          git pull origin main
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
          
          # Wait for app to start
          sleep 15
          
          # Health check
          if curl -f http://localhost:8080/health > /dev/null 2>&1; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed!"
            docker-compose logs
            exit 1
          fi 